services:
  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "8048:5000"
    volumes:
      - ./back-end:/app
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-frontend
    ports:
      - "8047:5173"
    volumes:
      - ./front-end:/app
      - ./front-end/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8048/api
    depends_on:
      - backend

networks:
  spm-net:
    name: spm-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.3.0/24
          gateway: 172.19.3.1