export const CONTAINER_VESSELS = new Set([
    'KM. ORIENTAL EMERALD',
    'KM. ORIENTAL RUBY',
    'KM. ORIENTAL SILVER',
    'KM. ORIENTAL GOLD',
    'KM. ORIENTAL JADE',
    'KM. ARMADA SEJATI',
    'KM. ORIENTAL DIAMOND',
    'KM. LUZON',
    'KM. BALI AYU',
    'KM. VERIZON',
    'KM. ORIENTAL GALAXY',
    'KM. HIJAU SAMUDRA',
    'KM. ARMADA PERMATA',
    'KM. ORIENTAL SAMUDERA',
    'KM. ORIENTAL PACIFIC',
    'KM. PULAU NUNUKAN',
    'KM. TELUK FLAMINGGO',
    'KM. TELUK BERAU',
    'KM. TELUK BINTUNI',
    'KM. PULAU LAYANG',
    'KM. PULAU WETAR',
    'KM. PULAU HOKI',
    'KM. SPIL HANA',
    'KM. SPIL HASYA',
    'KM. SPIL HAPSRI',
    'KM. SPIL HAYU',
    'KM. HIJAU JELITA',
    'KM. HIJAU SEJUK',
    'KM. ARMADA SERASI',
    'KM. ARMADA SEGARA',
    'KM. ARMADA SENADA',
    'KM. HIJAU SEGAR',
    'KM. TITANIUM',
    'KM. VERTIKAL',
    'KM. SPIL RENATA',
    'KM. SPIL RATNA',
    'KM. SPIL RUMI',
    'KM. PEKAN BERAU',
    'KM. SPIL RAHAYU',
    'KM. SPIL RETNO',
    'KM. MINAS BARU',
    'KM. PEKAN SAMPIT',
    'KM. SELILI BARU',
    'KM. DERAJAT',
    'KM. MULIANIM',
    'KM. PRATIWI RAYA',
    'KM. MAGELLAN',
    'KM. PAHALA',
    'KM. PEKAN RIAU',
    'KM. PEKAN FAJAR',
    'KM. FORTUNE',
    'KM. PRATIWI SATU',
    'KM. BALI GIANYAR',
    'KM. BALI KUTA',
    'KM. BALI SANUR',
    'KM. AKASHIA',
    'KM. KAPPA',
]);

export const MANALAGI_VESSELS = new Set([
    'KM. MANALAGI ASTA',
    'KM. MANALAGI ASTI',
    'KM. MANALAGI DASA',
    'KM. MANALAGI ENZI',
    'KM. MANALAGI HITA',
    'KM. MANALAGI SAMBA',
    'KM. MANALAGI TARA',
    'KM. MANALAGI TISYA',
    'KM. MANALAGI VIRA',
    'KM. MANALAGI WANDA',
    'KM. MANALAGI YASA',
    'KM. XYS SATU',
]);

export const BC_VESSELS = new Set([
    'BC. ANGSA LAUT',
    'BC. BALIKPAPAN RAYA',
    'BC. BANJARMASIN RAYA',
    'BC. BAYA',
    'BC. BELAWAN RAYA',
    'BC. EPSILON',
    'BC. GAJAH LAUT',
    'BC. GAJAH MADA',
    'BC. KAIMANA INDAH',
    'BC. MURO 5',
    'BC. SAMARINDA RAYA',
    'BC. SHORYU BARU',
    'BC. SURABAYA RAYA',
    'BC. TARAKAN RAYA',
    'BC. TENYO MARU',
]);

export const MT_VESSELS = new Set([
    'MT. GLOBAL',
    'MT. PANTAI LAMONG',
]);

export const TB_VESSELS = new Set([
    'TB. ALPHA',
    'TB. CAPUNG I',
    'TB. CAPUNG II',
    'TB. CAPUNG III',
    'TB. GAMMA SATU',
    'TB. MANGGA RAYA',
    'TB. SPIL BOAT',
    'TB. TOYO',
    'TB. YITNA YUWANA',
    'TB. YUSHIN MARU',
]);

export const TK_VESSELS = new Set([
    'TK. BETA SATU',
    'TK. DELTA DUA',
]);

export const OTHERS_VESSELS = new Set([
    'DARAT',
    'DARAT BIASA',
    'DARAT STAND-BY',
    'PENDING CUTI',
    'PENDING GAJI',
]);
